# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - "suggestion (plugin): added"
    - title: 🛠 Bug Fixes
      labels:
        - "bug: fixed"
    - title: 📖 Documentation
      labels:
        - "suggestion (documentation): added"
    - title: 👒 Dependencies
      labels:
        - dependencies
